[package]
name = "dloor-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "dloor"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
arboard.workspace = true
crossterm.workspace = true
dloor-core = { path = "../dloor-core" }
ratatui.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
